version: '3.8'

services:
    frontend:
        build: example-frontend/.
        container_name: frontend
        ports:
            - 5000:5000

    backend:
        build: example-backend/.
        container_name: backend
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        command: redis-server