version: '3.8'

services:
    frontend:
        build: example-frontend/.
        container_name: frontend
        ports:
            - 5000:5000

    backend:
        build: example-backend/.
        container_name: backend
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        depends_on:
            - redis
            - db
        
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        command: redis-server

    db:
        image: postgres:latest
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - ./database:/var/lib/postgresql/data