services:
    db:
        image: postgres
        restart: unless-stopped
        container_name: db
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./database:/var/lib/postgresql/data

    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
    
    backend:
        build: ./example-backend
        container_name: backend
        restart: unless-stopped
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        depends_on:
            - db
            - redis
    
    frontend:
        build: ./example-frontend
        container_name: frontend
        restart: unless-stopped
        depends_on:
            - backend
    
    proxy:
        image: nginx:alpine
        container_name: proxy
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - backend
            - frontend

volumes:
    database: